show databases;
use consumer_behavior_db;
select * from consumer_behavior limit 5;

-- Q1 what is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as revenue
from consumer_behavior
group by gender;

-- Q2 Which customer's used the discount but still spend more then the average purchase amount?
select customer_id, purchase_amount
from consumer_behavior
where discount_applied = 'Yes' and purchase_amount >= (select Avg(purchase_amount) from consumer_behavior);

-- Q3 Which are the top 5 products with the highest average review rating ?
select item_purchased, ROUND(avg(review_rating) ,2) as "Average Product Rating"
from consumer_behavior
group by item_purchased 
order by avg(review_rating) desc
limit 5;

-- Q4 Compare the average purchase amount between standard and express shipping
select shipping_type,
ROUND(AVG(purchase_amount),2)
from consumer_behavior 
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Q5 Do subscribed customer spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM consumer_behavior
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend;

-- Q6 Which 5 products have the highest percentage of purchase with discounts applied.
SELECT item_purchased,
       ROUND(
           SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
           / COUNT(*) * 100,
           2
       ) AS discount_rate
FROM consumer_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7 Segment customer into New, Returning and, Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
CASE
	When previous_purchases = 1 Then 'New'
    When previous_purchases Between 2 and 10 Then 'Returning'
    Else 'Loyal'
    End as customer_segment
from consumer_behavior 
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- Q8 What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id)desc) as item_rank
from consumer_behavior
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

-- Q9 Are customer who are repeat buyers (more then 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from consumer_behavior
where previous_purchases > 5
group by subscription_status;

-- Q10 What is the revenue contribution of each age group
select age_group,
sum(purchase_amount) as total_revenue
from consumer_behavior 
group by age_group
order by total_revenue desc;

use consumer_behavior_db;
select * from consumer_behavior;

